name: Ashtracker
description: Tracking Groundwater Contamination at Coal Combustion Waste Disposal Sites
contact:
  street: 1 Thomas Circle
  street_1: Suite 900
  city: Washington
  state: D.C.
  zipcode: 20005
  telephone: 202-296-8800
  fax: 202-296-8822
  email: officemanager@environmentalintegrity.org
copyright: Copyright (c) 2013 Ashtracker is brought to you by the Environmental Integrity Project. All rights reserved.
google:
  site_verification:
  analytics_account:
  analytics_domain:
sponsor:
  name: Environmental Integrity Project
  url: http://environmentalintegrity.org/
markdown: redcarpet
pygments: true
host: viableindustries.github.io/ashtracker
baseurl: /